### Importing all libraries

In [1]:
import torch

## Introduction to tensors

### Creating tensors

### Quick Scalar Rundown

A scalar is a single numerical value that represents a quantity without any directional information. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about scalars:

1. **Definition**: A scalar is a quantity that can be fully described by its magnitude (size or amount) alone.
2. **Contrast with vectors**: Unlike vectors, which have both magnitude and direction, scalars only have magnitude.
3. **Examples**:
    - ***Physics***: Temperature, mass, energy, time
    - ***Mathematics***: Real numbers, complex numbers
    - ***Computing***: Integer and floating-point variables
4. **Operations**: Scalars can be added, subtracted, multiplied, and divided using regular arithmetic operations.
5. **Programming**: In many programming languages, basic data types like integers and floats are scalar values.

In [2]:
# Scalar
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [3]:
# Show the number of dimensions of the scalar
scalar.ndim

0

In [4]:
# Get scalar back as Python integer
scalar.item()

7

### Quick Vector Rundown

A vector is a quantity that has both magnitude and direction. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about vectors:

1. **Definition**: A vector is a quantity that is fully described by both its magnitude (size or amount) and direction.
2. **Contrast with scalars**: Unlike scalars, which have only magnitude, vectors have both magnitude and direction.
3. **Examples**:
    - **Physics**: Velocity, force, displacement, acceleration
    - **Mathematics**: Ordered pairs/triplets, complex numbers (represented as points in a plane)
    - **Computing**: Arrays or lists that store multiple values
4. **Operations**: Vectors can be added, subtracted, scaled (multiplied by a scalar), and used in dot- and cross-products.
5. **Programming**: In many programming languages, data structures like arrays and lists can represent vectors.

In [5]:
# Vector
vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [6]:
# Show the number of dimensions of the vector
vector.ndim

1

In [7]:
# Get the shape of the vector
vector.shape

torch.Size([2])

### Quick Matrix Rundown

A matrix is an array of numbers arranged in rows and columns. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about matrices:

1. **Definition**: A matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.
2. **Dimensions**: The dimensions of a matrix are given by the number of rows and columns (e.g., a 3x2 matrix has 3 rows and 2 columns).
3. **Examples**:
    - **Mathematics**: Systems of linear equations, transformations in geometry
    - **Physics**: Representation of linear transformations, state vectors in quantum mechanics
    - **Computing**: Image data (pixels arranged in rows and columns), adjacency matrices in graph theory
4. **Operations**: Matrices can be added, subtracted, and multiplied. They can also be used in operations such as transposition, inversion, and finding determinants.
5. **Programming**: In many programming languages, matrices are implemented as two-dimensional arrays or lists of lists.



In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Show the number of dimensions of the matrix
MATRIX.ndim

2

In [10]:
# Print the 1st and 2nd element of the matrix
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [11]:
# Get the shape of the matrix
MATRIX.shape

torch.Size([2, 2])

### Quick Tensor Rundown

A tensor is a multidimensional array of numerical values that generalizes the concepts of scalars, vectors, and matrices. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about tensors:

1. **Definition**: A tensor is a multidimensional array of numbers that generalizes scalars (0-dimensional), vectors (1-dimensional), and matrices (2-dimensional) to higher dimensions.
2. **Dimensions (Ranks)**: The rank of a tensor refers to the number of dimensions (or indices) required to describe it. For example, a scalar is a rank-0 tensor, a vector is a rank-1 tensor, and a matrix is a rank-2 tensor.
3. **Examples**:
    - **Physics**: Stress and strain tensors in mechanics, the metric tensor in general relativity
    - **Mathematics**: Multi-linear maps, higher-order generalizations of matrices
    - **Computing**: Multidimensional arrays used in machine learning and data representation (e.g., images, video, and more complex datasets)
4. **Operations**: Tensors can undergo various operations such as addition, subtraction, multiplication (including dot product and tensor product), contraction, and transformations.
5. **Programming**: In many programming languages and frameworks (like TensorFlow and PyTorch), tensors are used to represent and manipulate data for machine learning and other numerical computations.

[Tensors explained](https://youtu.be/f5liqUk0ZTw).

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 8],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 8],
         [2, 4, 5]]])

In [13]:
# Show the number of dimensions of the tensor
TENSOR.ndim

3

In [14]:
# Get the shape of the matrix
TENSOR.shape

torch.Size([1, 3, 3])

<p>
    <img src="00_markdown_images/00-pytorch-different-tensor-dimensions.png" alt="Different Tensor Dimensions" width=720" height="360">
</p>

### Short Summary

### Let's Summarize

| Name    | What is it?                                                                                                               | Number of dimensions | Lower or upper (usually/example) |
|---------|---------------------------------------------------------------------------------------------------------------------------|----------------------|----------------------------------|
| Scalar  | A single number                                                                                                           | 0                    | Lower (a)                        |
| Vector  | A number with direction (e.g., wind speed with direction) but can also have many other numbers                            | 1                    | Lower (y)                        |
| Matrix  | A 2-dimensional array of numbers                                                                                          | 2                    | Upper (Q)                        |
| Tensor  | An n-dimensional array of numbers; can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector  | Can be any number    | Upper (X)                        |

<p>
    <img src="00_markdown_images/00-scalar-vector-matrix-tensor.png" alt="Scalar Vector Matrix Tensor" width=400" height="450">
</p>

## Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data. ->

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

In [15]:
# Create a random tensor of size/shape (3, 4)
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.3199, 0.7449, 0.7703, 0.5833],
        [0.4246, 0.2706, 0.9596, 0.1901],
        [0.5737, 0.2290, 0.3747, 0.4602]])

In [16]:
# Random tensor number of dimensions
random_tensor.ndim

2

In [17]:
# Random tensor shape
random_tensor.shape

torch.Size([3, 4])

In [18]:
# Create a random tensor with similar shape to an image tensor (height, width, color channels)
random_image_size_tensor = torch.rand(size=(224, 224, 3))

random_image_size_tensor

tensor([[[0.6476, 0.4868, 0.3507],
         [0.3873, 0.4266, 0.9485],
         [0.2625, 0.6449, 0.5773],
         ...,
         [0.7882, 0.6049, 0.9644],
         [0.0286, 0.3576, 0.3086],
         [0.9132, 0.3154, 0.2106]],

        [[0.1072, 0.2323, 0.7556],
         [0.2071, 0.5442, 0.3153],
         [0.5242, 0.9859, 0.7066],
         ...,
         [0.6798, 0.0463, 0.6390],
         [0.9600, 0.1971, 0.6520],
         [0.3519, 0.0079, 0.7263]],

        [[0.4923, 0.3351, 0.5836],
         [0.6045, 0.9333, 0.8202],
         [0.9221, 0.4450, 0.1965],
         ...,
         [0.3386, 0.3712, 0.8763],
         [0.1230, 0.8607, 0.1987],
         [0.0693, 0.0316, 0.2303]],

        ...,

        [[0.5696, 0.6102, 0.4652],
         [0.5218, 0.9311, 0.0158],
         [0.6745, 0.8310, 0.7311],
         ...,
         [0.8658, 0.6613, 0.3466],
         [0.6290, 0.3132, 0.3492],
         [0.9571, 0.3044, 0.4077]],

        [[0.1715, 0.0968, 0.7727],
         [0.0799, 0.4959, 0.4599],
         [0.

In [19]:
# Random tensor number of dimensions
random_image_size_tensor.ndim

3

In [20]:
# Random tensor shape
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [21]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Multiplying zeros tensor with random_tensor
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
# Data type of zeros, ones, random_tensor0
print(zeros.dtype)
print(ones.dtype)
print(random_tensor.dtype)

torch.float32
torch.float32
torch.float32


### Creating a range of tensors and tensors-like

In [25]:
# Using torch.arange(start, stop, step)
one_to_ten = torch.arange(1, 11, 1)

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Tensor Like
Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so, you can use `torch.zeros_like(input)` or `torch.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [26]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### [Tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types)

**NB!** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors are not the right datatype.
2. Tensors are not the right shape.
3. Tensors are not on the right device (CPU or CUDA).

In [27]:
# Float32 tensor <- This is the DEFAULT datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,  # What datatype is the tensor (e.g., float32, float16, etc.)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether to track gradients with these tensor operations.

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [28]:
# Float16 tensor
# In this case, we convert float_32_tensor to float16 tensor.
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
# Int32 Tensor
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors are not the right datatype -> To get the datatype of tensor, you can use `tensor.dtype`
2. Tensors are not the right shape -> To get the shape of the tensor, you can use `tensor.shape`.
3. Tensors are not on the right device -> To get the device from a tensor, you can use `tensor.device`.

In [30]:
# Creating a tensor
some_tensor = torch.rand(3, 4)

some_tensor

tensor([[0.9819, 0.0188, 0.3237, 0.4374],
        [0.4350, 0.5584, 0.7462, 0.2365],
        [0.9978, 0.4525, 0.6246, 0.9106]])

In [31]:
# Finding out information about the tensor
print(some_tensor)
print(f"The tensor's datatype is: {some_tensor.dtype}")
print(f"The tensor's shape is: {some_tensor.shape}")
print(f"The tensor's device is: {some_tensor.device}")


tensor([[0.9819, 0.0188, 0.3237, 0.4374],
        [0.4350, 0.5584, 0.7462, 0.2365],
        [0.9978, 0.4525, 0.6246, 0.9106]])
The tensor's datatype is: torch.float32
The tensor's shape is: torch.Size([3, 4])
The tensor's device is: cpu


### Manipulating Tensors
#### (Tensor Operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [32]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

tensor

tensor([1, 2, 3])

In [33]:
# Add 10 to the created tensor
print(tensor + 10)

# PyTorch built-in function `add`
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [34]:
# Multiply by 10 the created tensor
print(tensor * 10)

# PyTorch built-in function `mul`
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [35]:
# Subtract 10 from the tensor
print(tensor - 10)

# PyTorch built-in function `sub`
print(torch.sub(tensor, 10))

tensor([-9, -8, -7])
tensor([-9, -8, -7])


### Matrix multiplication

There are 2 main ways to multiply matrices:
1. Element-wise multiplication
2. Matrix multiplication (Dot product)

There are two main rues that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match: 
* `(3, `**2**`) @ (`**3**`, 2)` <-- Won't work.
* `(2, `**3**`) @ (`**3**`, 2)` <-- Will work.
* `(3, `**2**`) @ (`**2**`, 3)` <-- Will work.
2. The resulting matrix has the shape of the **outer dimensions**.
* `(`**2**`, 3) @ (3, `**2**`)` --> This matrix has the shape `(`**2**`, `**2**`)`
* `(`**3**`, 2) @ (2, `**3**`)` --> This matrix has the shape `(`**3**`, `**3**`)`

[Matrix multiplication training](http://matrixmultiplication.xyz)

In [36]:
# Element-wise matrix multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [37]:
%%time

# Matrix multiplication (Dot product)
torch.matmul(tensor, tensor)
# torch.mm(tensor, tensor) is the equivalent to the top line (line 4)

CPU times: user 102 μs, sys: 16 μs, total: 118 μs
Wall time: 123 μs


tensor(14)

In [38]:
%%time

# Matrix multiplication (Dot product) by hand
value = 0
print(f"Starting value is: {value}")

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    
    print(f"{tensor[i]} * {tensor[i]} = {tensor[i] * tensor[i]}")
    print(f"Current value is: {value}")

print(f"Final value is: {value}")

Starting value is: 0
1 * 1 = 1
Current value is: 1
2 * 2 = 4
Current value is: 5
3 * 3 = 9
Current value is: 14
Final value is: 14
CPU times: user 423 μs, sys: 1.91 ms, total: 2.33 ms
Wall time: 2.26 ms


### One of the most common errors in Deep Learning: ***Shape Errors***

In [39]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


# torch.mm is alias for torch.matmul
# torch.matmul(tensor_A, tensor_B) <-- This is invalid

In [40]:
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** switches the axes/dimensions of a given tensor.

In [41]:
# Original tensor_B
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [42]:
# Transposed tensor_B
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [43]:
# Working matrix multiplication, when tensor_B is transposed
print(f"Original shapes: \n\ttensor_A: {tensor_A.shape} \n\ttensor_B: {tensor_B.shape}")
print(f"New shapes:  \n\ttensor_A (Original): {tensor_A.shape} \n\ttensor_B (Transposed): {tensor_B.T.shape}")
print()

output = torch.matmul(tensor_A, tensor_B.T)

print(f"Multiplying {tensor_A.shape} @ {tensor_B.T.shape} <- Inner dimensions must match.")
print()

print(f"Matrix multiplication result: \n{output} \n{output.shape}")


Original shapes: 
	tensor_A: torch.Size([3, 2]) 
	tensor_B: torch.Size([3, 2])
New shapes:  
	tensor_A (Original): torch.Size([3, 2]) 
	tensor_B (Transposed): torch.Size([2, 3])

Multiplying torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner dimensions must match.

Matrix multiplication result: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) 
torch.Size([3, 3])


### Tensor aggregation
***Description, Simple:*** Going from more values to fewer values

***Description, Complex:*** The process of combining multiple tensors into a single tensor. It can be done in several ways depending on the specific requirements, such as summing tensors, averaging them, concatenating them along a specific axis, or applying other reduction operations.

Some of the viable operations: 
* Min
* Max
* Mean
* Sum
* Average
* Concatenation

In [44]:
# Create a tensor
x = torch.arange(0, 100, 10)

print(x)
print(x.shape)
print(x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.Size([10])
torch.int64


In [45]:
# Find the min value
print(torch.min(x))
print(x.min())

tensor(0)
tensor(0)


In [46]:
# Find the max value
print(torch.max(x))
print(x.max())

tensor(90)
tensor(90)


In [47]:
# Find the mean value
# Note: torch.mean() requires a tensor of float or complex dtype
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())

tensor(45.)
tensor(45.)


In [48]:
# Find the sum value
print(torch.sum(x))
print(x.sum())

tensor(450)
tensor(450)


### Finding positional min and max
***Description, Simple:*** Finding the index of a tensor where the max or minimum occurs.

***Description, Complex:*** Operations where the minimum or maximum values are identified along a specific dimension (*axis*) of a tensor, and the positions (*indices*) of these values are also returned.

***Operations:***
* `torch.argmax(tensor, dimension)` <- max identified value.
* `torch.argmin(tensor, dimension)` <- min identified value

In [49]:
# Positional min
print(f"The min index is: {x.argmin()}")
print(f"The min index is: {torch.argmin(x, dim=0)}")

The min index is: 0
The min index is: 0


In [50]:
# Positional max
print(f"The max index is: {x.argmax()}")
print(f"The min index is: {torch.argmax(x, dim=0)}")

The max index is: 9
The min index is: 9


## Reshaping, Stacking, Squeezing and Unsqueezing tensors
| Process          | Description                                                                                             | Method                        | Specific Function                                                                                             |
|------------------|---------------------------------------------------------------------------------------------------------|-------------------------------|---------------------------------------------------------------------------------------------------------------|
| **Reshaping**    | Reshapes an input tensor to a defined shape.                                                            | *torch.reshape(input, shape)* | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`.                           |
| **Viewing**      | Returns a view of an input tensor of a certain shape, but keeps the same memory as the original tensor. | *Tensor.view(shape)*          | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| **Stacking**     | Combining multiple tensors on top of each other (*vstack*) or side by side (*hstack*).                  | *torch.stack(tensors, dim=0)* | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be the same size.      |
| **Squeezing**    | Removing all `1` dimensions from a tensor.                                                              | *torch.squeeze(input)*        | Squeezes `input` to remove all the dimensions with value `1`.                                                 |
| **Unsqueezing**  | Adding a `1` dimension to a tensor.                                                                     | *torch.unsqueeze(input, dim)* | Returns `input` with a dimension value of `1` added at `dim`.                                                 |
| **Permuting**    | Returns a `view` of the original input with its dimensions permuted (*swapped*) in a certain way.       | *torch.permute(input, dims)*  | Returns a `view` of the original input with its dimensions permuted (rearranged) to `dims`.                   |

In [51]:
# Creating a tensor
x = torch.arange(1., 11.,)

print(f"{x} \n{x.shape} \n{x.dtype}")

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) 
torch.Size([10]) 
torch.float32


In [52]:
# Adding an extra dimension.
# The elements are compatible if the original tensor shape is equal multiplication of the arguments in the .reshape()
x_reshaped = x.reshape(5, 2)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

print()

x_reshaped = x.reshape(2, 5)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

print()

x_reshaped = x.reshape(10, 1)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

print()

x_reshaped = x.reshape(1, 10)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")



# # Invalid
# x_reshaped = x.reshape(2, 8)
# print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) 
torch.Size([5, 2]) 
torch.float32

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]) 
torch.Size([2, 5]) 
torch.float32

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]]) 
torch.Size([10, 1]) 
torch.float32

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) 
torch.Size([1, 10]) 
torch.float32


In [53]:
# Changing the view
z = x.view(1, 10)
print(z, z.shape)

# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
print(z, z.shape)
print(x, x.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])


In [54]:
# Stacking tensors

# Vertical stacking (vstack)
x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)

# Horizontal stacking (hstack)
x_stacked = torch.stack([x, x, x, x], dim=1)
print(x_stacked)

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])


In [55]:
# Squeezing a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print()

print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [56]:
# Unsqueezing a tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print()

print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

print()

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print()

print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])

Previous tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [57]:
# Permuting a tensor

# Creating an original tensor
x_original = torch.rand(size=(224, 224, 3))     # [height, width, color_channels]

# Permuting the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)    # Shifts axis to [color_channels, height, width]

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Selecting data from tensors (Indexing)

In [58]:
# Creating a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)

print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [59]:
# Index on the new tensor (dim=0)
print(x[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [60]:
# Index on the middle bracket (dim=1)
print(x[0][0])

tensor([1, 2, 3])


In [61]:
# Index on the most inner bracket (dim=2)
print(x[0][0][0])

tensor(1)


In [62]:
# Using ':' to select "All" of a target dimension.
print(x[:, 0])
print(x[:, :, 1])

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])


In [63]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])

tensor([5])


In [64]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(x[0, 0, :])

tensor([1, 2, 3])


In [65]:
# Index on x to return 9
print(x[0, 2, -1])

tensor(9)


In [66]:
# Index on x to return 3, 6, 9
print(x[:, :, -1])

tensor([[3, 6, 9]])


### PyTorch Tensors & NumPy