### Importing all libraries

In [1]:
import torch
import numpy as np

### PyTorch Tensors & NumPy

NumPy is a popular scientific Python numerical computing library. Because of this, PyTorch has functionality to interact with it.

* NumPy array -> PyTorch tensor ==> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy array ==> `torch.Tensor.numpy()`

In [2]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
# NumPy default dtype
print(array.dtype)


# PyTorch default dtype is float32.
# When converting from NumPy to PyTorch the default dtype is float64.


float64


'\nPyTorch default dtype is float32.\n\nWhen converting from NumPy to PyTorch the default dtype is float64.\n'

In [4]:
# Changing the value of the array, it won't change the value of the tensor if it is already created

array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
# Changing the value of the tensor, it won't change the value of the numpy_tensor if it is already created

tensor = tensor + 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### [Reproducibility](https://pytorch.org/docs/stable/notes/randomness.html) (Trying to take the random out of the random)

It is how neural networks learn: 

`Start with random numbers` -> `Tensor operations` -> `Update random numbers to try and make them better representations of the data` -> `Repeat` -> `Repeat` -> `Repeat` -> ...  

To reduce the randomness in neural networks and PyTorch comes the concept of a ***random seed***. 

Essential what the ***random seed*** is *flavours* the randomness.

In [17]:
# Creating two random tensors.
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.3259, 0.2802, 0.4159, 0.3756],
        [0.6616, 0.3169, 0.3772, 0.6858],
        [0.0242, 0.4616, 0.1515, 0.0505]])
tensor([[0.6260, 0.2720, 0.6491, 0.9899],
        [0.5792, 0.0744, 0.7387, 0.3218],
        [0.6462, 0.5225, 0.4348, 0.7732]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [19]:
# Creating random, but reproducible tensors

# Setting random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# The seed must be reset every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
