### Importing all libraries

In [1]:
import torch

### One of the most common errors in Deep Learning: ***Shape Errors***

In [2]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


# torch.mm is alias for torch.matmul
# torch.matmul(tensor_A, tensor_B) <-- This is invalid

In [3]:
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** switches the axes/dimensions of a given tensor.

In [4]:
# Original tensor_B
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [5]:
# Transposed tensor_B
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [6]:
# Working matrix multiplication, when tensor_B is transposed
print(f"Original shapes: \n\ttensor_A: {tensor_A.shape} \n\ttensor_B: {tensor_B.shape}")
print(f"New shapes:  \n\ttensor_A (Original): {tensor_A.shape} \n\ttensor_B (Transposed): {tensor_B.T.shape}")
print()

output = torch.matmul(tensor_A, tensor_B.T)

print(f"Multiplying {tensor_A.shape} @ {tensor_B.T.shape} <- Inner dimensions must match.")
print()

print(f"Matrix multiplication result: \n{output} \n{output.shape}")


Original shapes: 
	tensor_A: torch.Size([3, 2]) 
	tensor_B: torch.Size([3, 2])
New shapes:  
	tensor_A (Original): torch.Size([3, 2]) 
	tensor_B (Transposed): torch.Size([2, 3])

Multiplying torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner dimensions must match.

Matrix multiplication result: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) 
torch.Size([3, 3])


### Tensor aggregation
***Description, Simple:*** Going from more values to fewer values

***Description, Complex:*** The process of combining multiple tensors into a single tensor. It can be done in several ways depending on the specific requirements, such as summing tensors, averaging them, concatenating them along a specific axis, or applying other reduction operations.

Some of the viable operations: 
* Min
* Max
* Mean
* Sum
* Average
* Concatenation

In [7]:
# Create a tensor
x = torch.arange(0, 100, 10)

print(x)
print(x.shape)
print(x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.Size([10])
torch.int64


In [8]:
# Find the min value
print(torch.min(x))
print(x.min())

tensor(0)
tensor(0)


In [9]:
# Find the max value
print(torch.max(x))
print(x.max())

tensor(90)
tensor(90)


In [10]:
# Find the mean value
# Note: torch.mean() requires a tensor of float or complex dtype
print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())

tensor(45.)
tensor(45.)


In [11]:
# Find the sum value
print(torch.sum(x))
print(x.sum())

tensor(450)
tensor(450)


### Finding positional min and max
***Description, Simple:*** Finding the index of a tensor where the max or minimum occurs.

***Description, Complex:*** Operations where the minimum or maximum values are identified along a specific dimension (*axis*) of a tensor, and the positions (*indices*) of these values are also returned.

***Operations:***
* `torch.argmax(tensor, dimension)` <- max identified value.
* `torch.argmin(tensor, dimension)` <- min identified value

In [12]:
# Positional min
print(f"The min index is: {x.argmin()}")
print(f"The min index is: {torch.argmin(x, dim=0)}")

The min index is: 0
The min index is: 0


In [13]:
# Positional max
print(f"The max index is: {x.argmax()}")
print(f"The min index is: {torch.argmax(x, dim=0)}")

The max index is: 9
The min index is: 9


## Reshaping, Stacking, Squeezing and Unsqueezing tensors
| Process          | Description                                                                                             | Method                        | Specific Function                                                                                             |
|------------------|---------------------------------------------------------------------------------------------------------|-------------------------------|---------------------------------------------------------------------------------------------------------------|
| **Reshaping**    | Reshapes an input tensor to a defined shape.                                                            | *torch.reshape(input, shape)* | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`.                           |
| **Viewing**      | Returns a view of an input tensor of a certain shape, but keeps the same memory as the original tensor. | *Tensor.view(shape)*          | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| **Stacking**     | Combining multiple tensors on top of each other (*vstack*) or side by side (*hstack*).                  | *torch.stack(tensors, dim=0)* | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be the same size.      |
| **Squeezing**    | Removing all `1` dimensions from a tensor.                                                              | *torch.squeeze(input)*        | Squeezes `input` to remove all the dimensions with value `1`.                                                 |
| **Unsqueezing**  | Adding a `1` dimension to a tensor.                                                                     | *torch.unsqueeze(input, dim)* | Returns `input` with a dimension value of `1` added at `dim`.                                                 |
| **Permuting**    | Returns a `view` of the original input with its dimensions permuted (*swapped*) in a certain way.       | *torch.permute(input, dims)*  | Returns a `view` of the original input with its dimensions permuted (rearranged) to `dims`.                   |

In [14]:
# Creating a tensor
x = torch.arange(1., 11.,)

print(f"{x} \n{x.shape} \n{x.dtype}")

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) 
torch.Size([10]) 
torch.float32


In [15]:
# Adding an extra dimension.
# The elements are compatible if the original tensor shape is equal multiplication of the arguments in the .reshape()
x_reshaped = x.reshape(5, 2)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

print()

x_reshaped = x.reshape(2, 5)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

print()

x_reshaped = x.reshape(10, 1)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

print()

x_reshaped = x.reshape(1, 10)
print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")



# # Invalid
# x_reshaped = x.reshape(2, 8)
# print(f"{x_reshaped} \n{x_reshaped.shape} \n{x_reshaped.dtype}")

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) 
torch.Size([5, 2]) 
torch.float32

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]) 
torch.Size([2, 5]) 
torch.float32

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]]) 
torch.Size([10, 1]) 
torch.float32

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) 
torch.Size([1, 10]) 
torch.float32


In [16]:
# Changing the view
z = x.view(1, 10)
print(z, z.shape)

# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
print(z, z.shape)
print(x, x.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])


In [17]:
# Stacking tensors

# Vertical stacking (vstack)
x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)

# Horizontal stacking (hstack)
x_stacked = torch.stack([x, x, x, x], dim=1)
print(x_stacked)

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])


In [18]:
# Squeezing a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print()

print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [19]:
# Unsqueezing a tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print()

print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

print()

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print()

print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])

Previous tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [20]:
# Permuting a tensor

# Creating an original tensor
x_original = torch.rand(size=(224, 224, 3))     # [height, width, color_channels]

# Permuting the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)    # Shifts axis to [color_channels, height, width]

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Selecting data from tensors (Indexing)

In [21]:
# Creating a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)

print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [22]:
# Index on the new tensor (dim=0)
print(x[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [23]:
# Index on the middle bracket (dim=1)
print(x[0][0])

tensor([1, 2, 3])


In [24]:
# Index on the most inner bracket (dim=2)
print(x[0][0][0])

tensor(1)


In [25]:
# Using ':' to select "All" of a target dimension.
print(x[:, 0])
print(x[:, :, 1])

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])


In [26]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])

tensor([5])


In [27]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(x[0, 0, :])

tensor([1, 2, 3])


In [28]:
# Index on x to return 9
print(x[0, 2, -1])

tensor(9)


In [29]:
# Index on x to return 3, 6, 9
print(x[:, :, -1])

tensor([[3, 6, 9]])
