### Importing all libraries

In [1]:
import torch

## Introduction to tensors

### Creating tensors

### Quick Scalar Rundown

A scalar is a single numerical value that represents a quantity without any directional information. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about scalars:

1. **Definition**: A scalar is a quantity that can be fully described by its magnitude (size or amount) alone.
2. **Contrast with vectors**: Unlike vectors, which have both magnitude and direction, scalars only have magnitude.
3. **Examples**:
    - ***Physics***: Temperature, mass, energy, time
    - ***Mathematics***: Real numbers, complex numbers
    - ***Computing***: Integer and floating-point variables
4. **Operations**: Scalars can be added, subtracted, multiplied, and divided using regular arithmetic operations.
5. **Programming**: In many programming languages, basic data types like integers and floats are scalar values.

In [2]:
# Scalar
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [3]:
# Show the number of dimensions of the scalar
scalar.ndim

0

In [4]:
# Get scalar back as Python integer
scalar.item()

7

### Quick Vector Rundown

A vector is a quantity that has both magnitude and direction. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about vectors:

1. **Definition**: A vector is a quantity that is fully described by both its magnitude (size or amount) and direction.
2. **Contrast with scalars**: Unlike scalars, which have only magnitude, vectors have both magnitude and direction.
3. **Examples**:
    - **Physics**: Velocity, force, displacement, acceleration
    - **Mathematics**: Ordered pairs/triplets, complex numbers (represented as points in a plane)
    - **Computing**: Arrays or lists that store multiple values
4. **Operations**: Vectors can be added, subtracted, scaled (multiplied by a scalar), and used in dot- and cross-products.
5. **Programming**: In many programming languages, data structures like arrays and lists can represent vectors.

In [5]:
# Vector
vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [6]:
# Show the number of dimensions of the vector
vector.ndim

1

In [7]:
# Get the shape of the vector
vector.shape

torch.Size([2])

### Quick Matrix Rundown

A matrix is an array of numbers arranged in rows and columns. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about matrices:

1. **Definition**: A matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.
2. **Dimensions**: The dimensions of a matrix are given by the number of rows and columns (e.g., a 3x2 matrix has 3 rows and 2 columns).
3. **Examples**:
    - **Mathematics**: Systems of linear equations, transformations in geometry
    - **Physics**: Representation of linear transformations, state vectors in quantum mechanics
    - **Computing**: Image data (pixels arranged in rows and columns), adjacency matrices in graph theory
4. **Operations**: Matrices can be added, subtracted, and multiplied. They can also be used in operations such as transposition, inversion, and finding determinants.
5. **Programming**: In many programming languages, matrices are implemented as two-dimensional arrays or lists of lists.



In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Show the number of dimensions of the matrix
MATRIX.ndim

2

In [10]:
# Print the 1st and 2nd element of the matrix
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [11]:
# Get the shape of the matrix
MATRIX.shape

torch.Size([2, 2])

### Quick Tensor Rundown

A tensor is a multidimensional array of numerical values that generalizes the concepts of scalars, vectors, and matrices. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about tensors:

1. **Definition**: A tensor is a multidimensional array of numbers that generalizes scalars (0-dimensional), vectors (1-dimensional), and matrices (2-dimensional) to higher dimensions.
2. **Dimensions (Ranks)**: The rank of a tensor refers to the number of dimensions (or indices) required to describe it. For example, a scalar is a rank-0 tensor, a vector is a rank-1 tensor, and a matrix is a rank-2 tensor.
3. **Examples**:
    - **Physics**: Stress and strain tensors in mechanics, the metric tensor in general relativity
    - **Mathematics**: Multi-linear maps, higher-order generalizations of matrices
    - **Computing**: Multidimensional arrays used in machine learning and data representation (e.g., images, video, and more complex datasets)
4. **Operations**: Tensors can undergo various operations such as addition, subtraction, multiplication (including dot product and tensor product), contraction, and transformations.
5. **Programming**: In many programming languages and frameworks (like TensorFlow and PyTorch), tensors are used to represent and manipulate data for machine learning and other numerical computations.

[Tensors explained](https://youtu.be/f5liqUk0ZTw).

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 8],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 8],
         [2, 4, 5]]])

In [13]:
# Show the number of dimensions of the tensor
TENSOR.ndim

3

In [14]:
# Get the shape of the matrix
TENSOR.shape

torch.Size([1, 3, 3])

<p>
    <img src="00_markdown_images/00-pytorch-different-tensor-dimensions.png" alt="Different Tensor Dimensions" width=720" height="360">
</p>

### Short Summary

### Let's Summarize

| Name   | What is it?                                                                                      | Number of dimensions                                                           | Lower or upper (usually/example) |
|--------|--------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------|-----------------------------------|
| Scalar | A single number                                                                                  | 0                                                                             | Lower (a)                         |
| Vector | A number with direction (e.g., wind speed with direction) but can also have many other numbers   | 1                                                                             | Lower (y)                         |
| Matrix | A 2-dimensional array of numbers                                                                 | 2                                                                             | Upper (Q)                         |
| Tensor | An n-dimensional array of numbers; can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Can be any number                                                            | Upper (X)                         |


<p>
    <img src="00_markdown_images/00-scalar-vector-matrix-tensor.png" alt="Scalar Vector Matrix Tensor" width=360" height="450">
</p>

## Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data. ->

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

In [15]:
# Create a random tensor of size/shape (3, 4)
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.4807, 0.7709, 0.6916, 0.2526],
        [0.3469, 0.3696, 0.3429, 0.9013],
        [0.3884, 0.4091, 0.3846, 0.9007]])

In [16]:
# Random tensor number of dimensions
random_tensor.ndim

2

In [17]:
# Random tensor shape
random_tensor.shape

torch.Size([3, 4])

In [18]:
# Create a random tensor with similar shape to an image tensor (height, width, color channels)
random_image_size_tensor = torch.rand(size=(224, 224, 3))

random_image_size_tensor

tensor([[[0.8373, 0.4210, 0.4204],
         [0.1301, 0.0108, 0.0575],
         [0.8879, 0.9039, 0.5641],
         ...,
         [0.0371, 0.9864, 0.4333],
         [0.3010, 0.7964, 0.9966],
         [0.9693, 0.9531, 0.3183]],

        [[0.8054, 0.9981, 0.1853],
         [0.9475, 0.7716, 0.9165],
         [0.0224, 0.0315, 0.3042],
         ...,
         [0.9636, 0.6632, 0.9219],
         [0.2934, 0.1320, 0.4382],
         [0.3713, 0.6315, 0.6127]],

        [[0.3785, 0.2576, 0.0236],
         [0.5435, 0.5913, 0.2905],
         [0.7783, 0.2239, 0.1365],
         ...,
         [0.0903, 0.8099, 0.6404],
         [0.0181, 0.6948, 0.8036],
         [0.0051, 0.5158, 0.7213]],

        ...,

        [[0.0091, 0.3414, 0.9485],
         [0.2866, 0.3303, 0.5247],
         [0.1603, 0.9697, 0.5260],
         ...,
         [0.9426, 0.8670, 0.6744],
         [0.0866, 0.3731, 0.6641],
         [0.7677, 0.0431, 0.2108]],

        [[0.0385, 0.7612, 0.8707],
         [0.4161, 0.3024, 0.5103],
         [0.

In [19]:
# Random tensor number of dimensions
random_image_size_tensor.ndim

3

In [20]:
# Random tensor shape
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and Ones

In [21]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Multiplying zeros tensor with random_tensor
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
# Data type of zeros, ones, random_tensor0
print(zeros.dtype)
print(ones.dtype)
print(random_tensor.dtype)

torch.float32
torch.float32
torch.float32


### Creating a range of tensors and tensors-like

In [25]:
# Using torch.arange(start, stop, step)
one_to_ten = torch.arange(1, 11, 1)

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Tensor Like
Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so, you can use `torch.zeros_like(input)` or `torch.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [26]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### [Tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types)

**NB!** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors are not the right datatype.
2. Tensors are not the right shape.
3. Tensors are not on the right device (CPU or CUDA).

In [27]:
# Float32 tensor <- This is the DEFAULT datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,  # What datatype is the tensor (e.g., float32, float16, etc.)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether to track gradients with these tensor operations.

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [28]:
# Float16 tensor
# In this case, we convert float_32_tensor to float16 tensor.
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)