## Importing all needed libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to tensors

### Creating tensors

### Quick Scalar Rundown

A scalar is a single numerical value that represents a quantity without any directional information. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about scalars:

1. **Definition**: A scalar is a quantity that can be fully described by its magnitude (size or amount) alone.
2. **Contrast with vectors**: Unlike vectors, which have both magnitude and direction, scalars only have magnitude.
3. **Examples**:
    - ***Physics***: Temperature, mass, energy, time
    - ***Mathematics***: Real numbers, complex numbers
    - ***Computing***: Integer and floating-point variables
4. **Operations**: Scalars can be added, subtracted, multiplied, and divided using regular arithmetic operations.
5. **Programming**: In many programming languages, basic data types like integers and floats are scalar values.

In [2]:
# Scalar
scalar = torch.tensor(7)

print(scalar)

tensor(7)


In [3]:
# Show the number of dimension of the scalar
scalar.ndim

0

In [4]:
# Get scalar back as Python integer
scalar.item()

7

### Quick Vector Rundown

A vector is a quantity that has both magnitude and direction. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about vectors:

1. **Definition**: A vector is a quantity that is fully described by both its magnitude (size or amount) and direction.
2. **Contrast with scalars**: Unlike scalars, which have only magnitude, vectors have both magnitude and direction.
3. **Examples**:
    - **Physics**: Velocity, force, displacement, acceleration
    - **Mathematics**: Ordered pairs/triplets, complex numbers (represented as points in a plane)
    - **Computing**: Arrays or lists that store multiple values
4. **Operations**: Vectors can be added, subtracted, scaled (multiplied by a scalar), and used in dot and cross products.
5. **Programming**: In many programming languages, data structures like arrays and lists can represent vectors.



In [5]:
# Vector
vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [6]:
# Show the number of dimension of the vector
vector.ndim

1

In [7]:
# Get the shape of the vector
vector.shape

torch.Size([2])

### Quick Matrix Rundown

A matrix is an array of numbers arranged in rows and columns. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about matrices:

1. **Definition**: A matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.
2. **Dimensions**: The dimensions of a matrix are given by the number of rows and columns (e.g., a 3x2 matrix has 3 rows and 2 columns).
3. **Examples**:
    - **Mathematics**: Systems of linear equations, transformations in geometry
    - **Physics**: Representation of linear transformations, state vectors in quantum mechanics
    - **Computing**: Image data (pixels arranged in rows and columns), adjacency matrices in graph theory
4. **Operations**: Matrices can be added, subtracted, and multiplied. They can also be used in operations such as transposition, inversion, and finding determinants.
5. **Programming**: In many programming languages, matrices are implemented as two-dimensional arrays or lists of lists.



In [8]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Show the number of dimensions of the matrix
matrix.ndim

2

In [10]:
# Print the 1st and 2nd element of the matrix
print(matrix[0])
print(matrix[1])

tensor([7, 8])
tensor([ 9, 10])


In [11]:
# Get the shape of the matrix
matrix.shape

torch.Size([2, 2])

### Quick Tensor Rundown

A tensor is a multidimensional array of numerical values that generalizes the concepts of scalars, vectors, and matrices. It's a fundamental concept in mathematics, physics, and computer science. Here are some key points about tensors:

1. **Definition**: A tensor is a multidimensional array of numbers that generalizes scalars (0-dimensional), vectors (1-dimensional), and matrices (2-dimensional) to higher dimensions.
2. **Dimensions (Ranks)**: The rank of a tensor refers to the number of dimensions (or indices) required to describe it. For example, a scalar is a rank-0 tensor, a vector is a rank-1 tensor, and a matrix is a rank-2 tensor.
3. **Examples**:
    - **Physics**: Stress and strain tensors in mechanics, the metric tensor in general relativity
    - **Mathematics**: Multi-linear maps, higher-order generalizations of matrices
    - **Computing**: Multidimensional arrays used in machine learning and data representation (e.g., images, video, and more complex datasets)
4. **Operations**: Tensors can undergo various operations such as addition, subtraction, multiplication (including dot product and tensor product), contraction, and transformations.
5. **Programming**: In many programming languages and frameworks (like TensorFlow and PyTorch), tensors are used to represent and manipulate data for machine learning and other numerical computations.

In [12]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 8],
                        [2, 4, 5]]])

tensor

tensor([[[1, 2, 3],
         [3, 6, 8],
         [2, 4, 5]]])

In [13]:
# Show the number of dimensions of the tensor
tensor.ndim

3

In [14]:
# Get the shape of the matrix
tensor.shape

torch.Size([1, 3, 3])

<p>
    <img src="00_markdown_images/00-pytorch-different-tensor-dimensions.png" alt="Different Tensor Dimensions" width=720" height="360">
</p>