# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)
tensor_A

tensor([[0.5636, 0.4976, 0.3903, 0.8095, 0.0173, 0.5561, 0.0260],
        [0.1386, 0.1299, 0.5985, 0.5748, 0.6326, 0.9978, 0.7879],
        [0.8949, 0.1532, 0.6233, 0.8523, 0.4722, 0.4495, 0.1289],
        [0.5059, 0.9861, 0.2380, 0.0600, 0.2097, 0.2225, 0.6611],
        [0.6394, 0.7105, 0.8743, 0.9008, 0.6430, 0.9031, 0.4949],
        [0.7495, 0.5117, 0.0076, 0.1252, 0.8419, 0.2175, 0.3192],
        [0.4432, 0.7322, 0.9994, 0.1683, 0.4773, 0.3261, 0.6709]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_B = torch.rand(1, 7)

# Perform matrix multiplication 

result_matmul = torch.matmul(tensor_A, tensor_B.T)
result_matmul

tensor([[1.6008],
        [1.8799],
        [1.8958],
        [1.2028],
        [2.6219],
        [1.2014],
        [1.6716]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
MANUAL_SEED = torch.manual_seed(0)

# Create two random tensors
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
gpu_tensor_A = torch.rand(size=(2, 3)).to(device)
gpu_tensor_B = torch.rand(size=(2, 3)).to(device)

gpu_tensor_A, gpu_tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
gpu_tensor_matmul = torch.matmul(gpu_tensor_A, gpu_tensor_B.T)

gpu_tensor_matmul, gpu_tensor_matmul.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max_value = torch.max(gpu_tensor_matmul)

# Find min
min_value = torch.min(gpu_tensor_matmul)

max_value, min_value

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
arg_max_value = torch.argmax(gpu_tensor_matmul)

# Find arg min
arg_min_value = torch.argmin(gpu_tensor_matmul)

arg_max_value, arg_min_value

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
NEW_SEED = torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor)
print(squeezed_tensor)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
