Tensor in Math: Mathematical object that is used to generalize scalars, vectors and matrices to higher dimensions.
Tensor in AI: Fundamental data structures, representing and manipulating multidimensional data. Tensors can be used to represent input data, store model parameters and perform computations efficiently.

In [1]:
# Import all required library
import torch

Creating a tensor

**NB! By default in PyTorch, all created tensors are float32-bit value!**

The created tensor is a 5x3 matrix, filled with zeros.

In [2]:
# Define tensor
z = torch.zeros(5, 3)

# Print tensor and it's type
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


Creating an integer tensor.

In that case we override default float32 values to integer value. PyTorch reports the new data type when the tensor is printed, to notify that the default value is not used and what tata type is being currently used.

In [3]:
i = torch.ones((5, 3), dtype=torch.int16)

print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


Initializing learning weights randomly is common practise. It is often used with a specific seed for the PRNG (PyTorch Random Number Generator) for reproducibility of results.

In [4]:
# Defining specific seed
torch.manual_seed(1729)

# Generating 1st random tensor
r1 = torch.rand(2, 2)

print("1st random tensor: ")
print(r1)

# Generating 2nd random tensor
r2 = torch.rand(2, 2)

print("2nd random tensor: ")
print(r2)

# Using the same seed and creating a 3rd random seed
# The generated result should match the result from the 1st generated seed, because of re-seeding.
torch.manual_seed(1729)

r3 = torch.rand(2, 2)

print("3rd random seed should match r1: ")
print(r3)

1st random tensor: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
2nd random tensor: 
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
3rd random seed should match r1: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


Arithmetic operations between tensors

In [6]:
# Generating tensor of ones
ones = torch.ones(2, 3)
print(ones)
print(ones.shape)

# Generating tensor of ones, where each element is multiplied by 2 to receive a tensor of twos
twos = torch.ones(2, 3) * 2
print(twos)
print(twos.shape)

# Creating a tensors of threes by adding the ones and twos tensors 
# This is possible because of the same shape of the tensors.
# The tensors are added element-wise.
threes = ones + twos
print(threes)
print(threes.shape)

# # Creating 2 random tensors with different shapes and adding them together will result in a runtime error.
# r1 = torch.rand(2, 3)
# r2 = torch.rand(3, 2)
# r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
torch.Size([2, 3])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


Some of the mathematical operations available in PyTorch

In [10]:
# Values between -1 and +1
r = (torch.rand(2, 2) - 0.5) * 2
print("A random matrix, r: ")
print(r)

# Absolute value (Mathematical operations are supported)
print("\nAbsolute value of r: ")
print(torch.abs(r))

# asin (Trigonometric functions are supported)
print("\nInverse sine of r: ")
print(torch.asin(r))

# Determinant and singular value decomposition (Linear algebra operations)
print("\nDeterminant of r: ")
print(torch.det(r))

print("\nSingular value decomposition r: ")
print(torch.svd(r))

# Average and standard deviation & maximum value (Statistical and Aggregate operations)
print("\nDAverage and standard deviation of r: ")
print(torch.std_mean(r))

print("\nMaximum value of r: ")
print(torch.max(r))

A random matrix, r: 
tensor([[ 0.9956, -0.2232],
        [ 0.3858, -0.6593]])

Absolute value of r: 
tensor([[0.9956, 0.2232],
        [0.3858, 0.6593]])

Inverse sine of r: 
tensor([[ 1.4775, -0.2251],
        [ 0.3961, -0.7199]])

Determinant of r: 
tensor(-0.5703)

Singular value decomposition r: 
torch.return_types.svd(
U=tensor([[-0.8353, -0.5497],
        [-0.5497,  0.8353]]),
S=tensor([1.1793, 0.4836]),
V=tensor([[-0.8851, -0.4654],
        [ 0.4654, -0.8851]]))

DAverage and standard deviation of r: 
(tensor(0.7217), tensor(0.1247))

Maximum value of r: 
tensor(0.9956)
