### Importing all libraries

In [1]:
import torch
import numpy as np

### PyTorch Tensors & NumPy

NumPy is a popular scientific Python numerical computing library. Because of this, PyTorch has functionality to interact with it.

* NumPy array -> PyTorch tensor ==> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy array ==> `torch.Tensor.numpy()`

In [2]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
# NumPy default dtype
print(array.dtype)


# PyTorch default dtype is float32.
# When converting from NumPy to PyTorch the default dtype is float64.


float64


In [4]:
# Changing the value of the array, it won't change the value of the tensor if it is already created

array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
# Changing the value of the tensor, it won't change the value of the numpy_tensor if it is already created

tensor = tensor + 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### [Reproducibility](https://pytorch.org/docs/stable/notes/randomness.html) (Trying to take the random out of the random)

It is how neural networks learn: 

`Start with random numbers` -> `Tensor operations` -> `Update random numbers to try and make them better representations of the data` -> `Repeat` -> `Repeat` -> `Repeat` -> ...  

To reduce the randomness in neural networks and PyTorch comes the concept of a ***random seed***. 

Essential what the ***random seed*** is *flavours* the randomness.

In [7]:
# Creating two random tensors.
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.4995, 0.0317, 0.2151, 0.6303],
        [0.7915, 0.7303, 0.1681, 0.7414],
        [0.0739, 0.6661, 0.7058, 0.6567]])
tensor([[0.5641, 0.6538, 0.7594, 0.2562],
        [0.7699, 0.4390, 0.2472, 0.5622],
        [0.7354, 0.4502, 0.2318, 0.6287]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [8]:
# Creating random, but reproducible tensors

# Setting random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# The seed must be reset every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Putting tensors (and models) on the GPU

Tensors/Models on the GPU results in faster computation times. 

In [9]:
# Creating a tensor (default is on the CPU)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
# Move tensor on GPU (if available)
tensor_on_gpu = tensor.to(device="cuda")
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

* NumPy does not work with the GPU

In [11]:
# # Move tensor to CPU
# tensor_on_gpu.numpy()   # It will return error

In [12]:
# To fix GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

print(tensor_back_on_cpu)
print(tensor_on_gpu)

[1 2 3]
tensor([1, 2, 3], device='cuda:0')
